server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    min-response-size: 1024


spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 123456

logging:
  level:
    root: INFO
    org:
      neo4j:
        driver:
          Driver: DEBUG

endpoints:
  default:
    web:
      enabled: true
